#!/usr/bin/env bash
# Configures Nginx to return 'Hello Holberton' and HTTP 200 on port 80

# Create a custom Nginx config file
cat << 'EOF' > /etc/nginx/http.d/default.conf
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        default_type text/plain;
        return 200 'Hello Holberton';
    }
}
EOF

# Reload Nginx to apply new config
nginx -s reload || nginx

