#!/usr/bin/env bash
# Script to install nginx and configure a 301 redirect from /redirect_me

# Update and install nginx
apt-get update -y
apt-get install nginx -y

# Set up the redirect using sed by inserting into default server block
sed -i '/location \/ {/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart nginx using service (not systemctl)
service nginx restart
