#!/usr/bin/env bash
# Script to install nginx and configure a custom 404 page

# Update and install nginx
apt-get update -y
apt-get install nginx -y

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Configure nginx to use the custom 404 page
sed -i '/error_page 404 \/404.html;/c\    error_page 404 \/custom_404.html;' /etc/nginx/sites-available/default

# Restart nginx (not using systemctl)
service nginx restart
"
